const data =[
    {
        id:1,
        timestamp:'10:00 am',
        priority:1,
        description:"",
        color:"red",
        status:true,
    },
    {
        id:2,
        timestamp:'10:30 am',
        priority:2,
        description:"",
        color:"HotPink",
        status:true,
    },
    {
        id:3,
        timestamp:'11:00 am',
        priority:3,
        description:"",
        color:"orange",
        status:true,
    },
    {
        id:4,
        timestamp:'11:30 am',
        priority:4,
        description:"",
        color:"yellow",
        status:true,
    },
    {
        id:5,
        timestamp:'12:00 pm',
        priority:5,
        description:"",
        color:"Aquamarine",
        status:true,
    },
    {
        id:6,
        timestamp:'12:30 pm',
        priority:1,
        description:"",
        color:"red",
        status:true,
    },
    {
        id:7,
        timestamp:'01:00 pm',
        priority:2,
        description:"",
        color:"HotPink",
        status:true,
    },
    {
        id:8,
        timestamp:'01:30 pm',
        priority:3,
        description:"",
        color:"orange",
        status:true,
    },
    {
        id:9,
        timestamp:'02:00 pm',
        priority:4,
        description:"Hello i am desc",
        color:"yellow",
        status:false,
    },
]
export default data;